# Use an official Node.js image as the base image
FROM node:latest

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port the backend will run on (default for Express is 5000)
EXPOSE 5000

# Set environment variables for JWT_SECRET and MONGO_URI, to be injected by Jenkins or Docker Compose
ENV JWT_SECRET=${JWT_SECRET}
ENV MONGO_URI=${MONGO_URI}

# Run the backend application
CMD ["npm", "start"]
