version: '3'

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002

  subtask-service:
    build: ./subtask-service
    container_name: subtask-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003

  search-service:
    build: ./search-service
    container_name: search-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004

  task-visualization-service:
    build: ./task-visualization-service
    container_name: task-visualization-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - PORT=3005
