services:
  frontend:
    build:
      context: ./taskapp-frontend  # Ensure the context is set to the correct path
    container_name: taskapp-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      
  user-service:
    build:
      context: ./task-backend/user-service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    depends_on:
      - frontend

  task-service:
    build:
      context: ./task-backend/task-service
    container_name: task-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
    depends_on:
      - frontend

  subtask-service:
    build:
      context: ./task-backend/subtask-service
    container_name: subtask-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
    depends_on:
      - frontend

  search-service:
    build:
      context: ./task-backend/search-service
    container_name: search-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
    depends_on:
      - frontend

  task-visualization-service:
    build:
      context: ./task-backend/task-visualization-service
    container_name: task-visualization-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - PORT=3005
    depends_on:
      - frontend
