# Stage 1: Build Stage
FROM node:14-alpine as build-stage

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install dependencies including dev dependencies
RUN npm install --production=false

# Copy the rest of the React app code
COPY . .

# Build the React app
RUN npm run build

# Stage 2: Production Stage
FROM nginx:alpine

# Copy the build output from the build stage
COPY --from=build-stage /usr/src/app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
